### ISSUE TITLE
Does not work with Gnome 3 scaling

### ISSUE THREAD

**Issue by aufau** [XQF/xqf#222] opened 2019-08-08 17:28 UTC
![xqf-scaling](https://user-images.githubusercontent.com/4474909/62724032-5d5c0480-ba12-11e9-9060-52758b024358.png)
Text and icons are squashed, works ok with scaling set to 100%.

**Comment by illwieckz** [comment] 2019-08-08 20:37
Have you restarted it after having scaled? I experienced similar issues with some other GTK apps (hexchat for example) and in my case restarting the app fixed it.

XQF still relies on an old GTK (GTK2), so maybe you need to restart XQF after having rescaled the desktop.

**Comment by illwieckz** [comment] 2019-08-08 20:45
Hmm, I reproduce the issue and restarting XQF does not fix it on my end… Too bad…

Since it's related to GTK2 and since the proper fix seems to be to finish the GTK3 port, I currently close this issue in favor of #14 that is tracking GTK3 port.

If someones finds a way to workaround the issue in GTK2 with a workaround that requires far less work than finishing the GTK3 port, please reopen this issue.

**Closed by illwieckz** 2019-08-08 20:45 UTC
